--
-- PostgreSQL database dump
--

--
-- TOC entry 3420 (class 0 OID 16961)
-- Dependencies: 224
-- Data for Name: awards; Type: TABLE DATA; Schema: public; Owner: lsa
--

INSERT INTO public.awards VALUES (1, '25-pen', 'stationary', 25, 'Cross® Pen', '<p>This Cross® Calais chrome and blue lacquer rollerball pen is lightweight with a bold profile. Pen has "25 Years" engraved on the lid.</p>', 'https://longserviceawards.gww.gov.bc.ca/wp-content/uploads/2022/03/pen-compass.jpg', 70, true);
INSERT INTO public.awards VALUES (2, '25-case', 'luggage', 25, 'Bugatti® Padfolio', '<p>This recycled and synthetic leather case has "25 Years" debossed on the front. It has adjustable brackets which hold most tablet models, including three sizes of iPad. The cover includes a pocket for a smartphone, USB dongle and pen holders, card slots, an ID window and writing pad. 9" x 10.75"</p>', 'https://longserviceawards.gww.gov.bc.ca/wp-content/uploads/2022/03/bugatti-padfolio-compass.jpg', 57, true);
INSERT INTO public.awards VALUES (3, '25-tags', 'luggage', 25, 'Passport and Luggage Tag Set', '<p>This navy blue, genuine leather passport holder and luggage tag set has "25 Years" debossed on the front. Both items feature a magnetic closure.</p>', 'https://longserviceawards.gww.gov.bc.ca/wp-content/uploads/2023/03/25-embossed-luggage-tags.jpg', 12, true);
INSERT INTO public.awards VALUES (4, '25-pearl-earrings', 'earrings', 25, 'Pearl earrings', '<p>These sterling silver freshwater pearl earrings have an accent of gold. They are made in Vancouver, B.C. by Howling Dog Artisan Jewellery. Size: 2.5 cm long by 1 cm wide.</p>', 'https://longserviceawards.gww.gov.bc.ca/wp-content/uploads/2022/03/pearl-earrings-compass.jpg', -1, true);
INSERT INTO public.awards VALUES (5, '25-serving-board', 'other', 25, 'Slate serving board', '<p>This serving board comes with a stainless steel cheese knife and and three cheese markers. Engraved with the BC Coat of Arms and "25 Years". 12" x 9"</p>', 'https://longserviceawards.gww.gov.bc.ca/wp-content/uploads/2022/03/slate-serving-tray-compass.jpg', -1, true);


INSERT INTO public.awards VALUES (6, '30-clock', 'clock', 30, 'Rothsbury silver table clock', '<p>The solid aluminum case of this timepiece has polished bevels with a brushed aluminum top and sides. It’s lightweight yet durable, and it has felt on the bottom to protect your surfaces. Place the Rothbury silver table clock on your mantel or desk as a functional accent piece. It has classic Roman numerals and a silver-finished skeleton movement dial for refined style. 6.25" x 7.75" x 2.25"</p>', 'https://longserviceawards.gww.gov.bc.ca/wp-content/uploads/2022/03/rothsbury-clock-compass.jpg', -1, true);
INSERT INTO public.awards VALUES (7, '30-silver-earrings', 'earrings', 30, 'Sterling silver earrings', '<p>These sterling silver drop earrings are individually handcrafted by B.C. artists Nancy Dawson and Vincent Henson of Silver Eagles Design Studio in Alert Bay. They come in a presentation box with, "In recognition of thirty years of service" engraved on the top. These earrings are intended to coordinate with the 35 year sterling silver bracelet. 2.75 cm long, 2 cm wide.</p>', 'https://longserviceawards.gww.gov.bc.ca/wp-content/uploads/2022/03/silver-earrings-compass.jpg', -1, true);
INSERT INTO public.awards VALUES (8, '30-blanket', 'other', 30, 'Appalachian Sherpa Blanket', '<p>This high-end plush blanket has "30 Years" embroidered on the corner. It’s made of faux suede on one side and soft Sherpa fleece on the other. 60" x 50"</p>', 'https://longserviceawards.gww.gov.bc.ca/wp-content/uploads/2022/03/blanket-compass.jpg', -1, true);
INSERT INTO public.awards VALUES (9, '30-elements', 'print', 30, '"Elements" Art Print', '<p>By B.C. artist Derek Thomas. This print is printed on fine art card stock, then framed with off-green matting and inner contrast colour and dark-grey frame. </p><p> "In recognition of thirty years of service" is engraved on a plaque. 13" x 15"</p>', 'https://longserviceawards.gww.gov.bc.ca/wp-content/uploads/2022/03/elements-painting-compass.jpg', -1, false);
INSERT INTO public.awards VALUES (10, '30-LoonDance', 'print', 30, '"Loon Dance II" Art Print', '<p>By B.C. artist Isaac Bignell Printed on canvas, this piece is framed in black with off-white matting and black inner-matting. </p><p> "In recognition of thirty years of service" is engraved on a plaque. 15" x 16"</p>', 'https://longserviceawards.gww.gov.bc.ca/wp-content/uploads/2022/03/loon-dance-painting-compass.jpg', -1, false);


INSERT INTO public.awards VALUES (11, '35-bulova', 'watch', 35, 'Bulova® watch', '<p>This watch features the BC Coat of Arms on the dial and can be personalized with your name and "35 years" engraved on the back. It comes in a choice of gold, silver or two-toned construction with a plated, black or brown leather strap.</p><p>Please read and select from the following options carefully.</p>', 'https://longserviceawards.gww.gov.bc.ca/wp-content/uploads/2023/03/35-Bulova-watches.jpg', -1, true);
INSERT INTO public.awards VALUES (12, '35-binoculars', 'other', 35, 'Bushnell® Prime binoculars', '<p>The Bushnell® Prime 10 x 42 binoculars provide a lightweight, durable and waterproof construction that will weather any storm/conditions/environment. The BAK4 phase coated prisms, and fully multi-coated optics ensure excellent low light performance and clarity when it matters most.-Exclusive EXO Barrier Protection: Bushnell''s newest and best protective lens coating molecularly bonds to the glass, repelling water, oil, dust, debris and preventing scratches.-IPX7 Waterproof construction: O-ring sealed optics stay dry inside, when immersed in three feet of water for up to 30 minutes.-Multi Coated Optics: Multiple layers of coatings on all lens surfaces increase light transmission and image brightness.
</p>', 'https://longserviceawards.gww.gov.bc.ca/wp-content/uploads/2023/03/35-bushnell-prime-binoculars.jpg', -1, true);
INSERT INTO public.awards VALUES (13, '35-bracelet', 'bracelet', 35, '<p>Sterling silver bracelet', '<p>This sterling silver bracelet is handcrafted by B.C. artists Nancy Dawson and Vincent Henson of Silver Eagles Design Studio, in Alert Bay. It comes in a box with, "In recognition of thirty five years of service"</p>', 'https://longserviceawards.gww.gov.bc.ca/wp-content/uploads/2022/03/bracelet-compass.jpg', -1, true);
INSERT INTO public.awards VALUES (14, '35-bowl', 'pottery', 35, 'Pottery Oyster Bowl', '<p>Deep oven, microwave and dishwasher save. This stunning show piece will be a treasure on your table for years to come. Please note, this is a handmade pottery shell bowl and colour tones may vary slightly from piece to piece. Made in BC by Mussels and More pottery. 20.5" x 10" x 3.5"</p>', 'https://longserviceawards.gww.gov.bc.ca/wp-content/uploads/2022/03/oyster-shell-bowl-compass.jpg', -1, false);


INSERT INTO public.awards VALUES (15, '40-bracket-clock', 'clock', 40, 'Graham Bracket III Howard Miller mantel Clock', '<p>This beautiful Howard Miller mantle clock is finished in Windows cherry wood. The brass finished dial offers a silver chapter ring and decorative corner spandrels. Quartz battery-operated German movement plays full Westminster or Ave Maria chimes with strike at hour and optional 4/4 chime feature, playing at 1/4, 1/2 and 3/4 chimes. Volume control and nighttime volume reductions option included. "In recognition of forty years of service" is engraved on a plaque. </p><p> Overall dimensions: 10.5" x 14.25" x 6.5"  </p>', 'https://longserviceawards.gww.gov.bc.ca/wp-content/uploads/2022/03/Graham-bracket-clock-compass.jpg', -1, true);
INSERT INTO public.awards VALUES (16, '40-diamond-necklace', 'necklace', 40, '<p>Genuine diamond pendant and chain', '<p>This necklace features a 10 kt white gold, four claw pendant and 18 inch box chain. The round, brilliant cut diamonds are 0.20 carat total weight. It comes in a presentation box with, "In recognition of fort years of service" engraved on the top.</p>', 'https://longserviceawards.gww.gov.bc.ca/wp-content/uploads/2022/03/diamond-necklace-compass.jpg', -1, false);
INSERT INTO public.awards VALUES (17, '40-diamond-earrings', 'earrings', 40, '<p>Genuine diamond stud earrings', '<p>These 14 kt white gold stud earrings feature brilliant round cut diamonds, 0.25 carat total weight. The Earrings have four white gold claws and butterfly backs. Presented in a box engraved with "In recognition of forty years of service."</p>', 'https://longserviceawards.gww.gov.bc.ca/wp-content/uploads/2022/03/diamond-earrings-compass.jpg', -1, true);
INSERT INTO public.awards VALUES (18, '40-bowl-mugs', 'pottery', 40, 'Large Mussel Shell Bowl and Two Matching Mugs', '<p>Simply stunning, this three-piece set is just gorgeous! Made of high fired porcelain clay. Oven, microwave and dishwasher safe. Please note, this is a handmade pottery shell bowl and color tones may vary slightly from piece to piece.</p><p>Made in B.C. by Mussels and More Pottery</p><p>Size: 20.5 x 8.5 x 4 inches</p>', 'https://longserviceawards.gww.gov.bc.ca/wp-content/uploads/2022/03/mussel-bowl-mug-set-compass.jpg', -1, true);
INSERT INTO public.awards VALUES (19, '40-beach-print', 'print', 40, '“Somewhere on the Beach” art print', '<p>By top B.C. artist Wani Pasion This art print is double matted in cream and natural beige, accented with a beautiful silver frame.</p><p> "In recognition of forty years of service" engraved on a plaque. Size approx: 17 x 22 in.</p>', 'https://longserviceawards.gww.gov.bc.ca/wp-content/uploads/2022/03/somewhere-on-the-beach-compass.jpg', -1, false);


INSERT INTO public.awards VALUES (20, '45-whale-tail', 'print', 45, '"Whale Tail" Art Print', '<p>By B.C. artist Pauline Bull. Printed on canvas, framed in black with double groove. </p><p>  "In recognition of forty five years of service" is engraved on a plaque. Size: 18" x 24"</p>', 'https://longserviceawards.gww.gov.bc.ca/wp-content/uploads/2022/03/Whale-tail-print-compass.jpg', -1, false);
INSERT INTO public.awards VALUES (21, '45-akron-clock', 'clock', 45, 'Akron Howard Miller mantel clock', '<p>This  beautiful Howard Miller mantel clock is  finished in Windsor cherry wood. This bracket -style  clock is embellished with  stylish details including a  brass  finished handle, reeded columns  and turned  caps, and matching reeded base frame with a  decorative dial. Quartz battery operated, German  made movement plays full Westminster or Ave  Maria chimes with strike on the hour.  Optional 4/4 chime feature which play 1/4, 1/2 and 3/4 chimes.  Volume control and nighttime volume reduction  option.  Takes two C batteries (not included).  “In  recognition of forty-five years of service”  engraved on a plaque. 12" x 16.5" x 7"</p>', 'https://longserviceawards.gww.gov.bc.ca/wp-content/uploads/2022/03/Akron-mantel-clock-compass.jpg', -1, true);
INSERT INTO public.awards VALUES (22, '45-luggage', 'luggage', 45, 'Thule® Subterra Luggage', '<p>This durable luggage from Thule is made from water-resistant materials. The tough, oversized wheels and V-Tubing telescoping handles make for smooth and easy transport. It has a divided main compartment to separate clothes and has top, side and bottom handles. Complies with carry-on requirements for most airlines. Size: 21.7 x 13.8 x 7.9 inches.</p>', 'https://longserviceawards.gww.gov.bc.ca/wp-content/uploads/2022/03/45-thule-luggage-compass.jpg', -1, false);
INSERT INTO public.awards VALUES (23, '45-telescope', 'other', 45, 'Carson® Telescope', '<p>With the RP-200SP 25-56x80mm Refractor Telescope can take pictures or video of the night sky. Adaptor accommodates all popular smartphones on the market. The telescope features fully coated optics and a durable aluminum tripod. It also has a Horizon mount with slow motion cables for tracking of celestial objects. It features an 8x21mm finder scope, two eyepieces and an erecting prism. Comes with a K20mm and K9mm eyepiece.</p>', 'https://longserviceawards.gww.gov.bc.ca/wp-content/uploads/2022/03/telescope-red-planet-compass.jpg', -1, false);
INSERT INTO public.awards VALUES (24, '45-diamond-earrings', 'earrings', 45, 'Genuine Diamond Stud Earrings', '<p>These 14 kt white gold stud earrings feature brilliant round cut diamonds, 0.25 carat total weight. The Earrings have four white gold claws and butterfly backs. Presented in a box engraved with "In recognition of forty-five years of service."</p>', 'https://longserviceawards.gww.gov.bc.ca/wp-content/uploads/2022/03/diamond-earrings-compass.jpg', -1, true);
INSERT INTO public.awards VALUES (25, '45-earrings-bracelet', 'bracelet', 45, 'Sterling Silver Bracelet and Earrings', '<p>This matching sterling silver cuff bracelet and drop earrings are handcrafted by B.C. artists Nancy Dawson and Vincent Henson of Silver Eagles Design Studio. It comes in a box with “In recognition of forty-five years of service” engraved on the top.</p><p>Cuff is 0.75 inch wide and comes in two sizes:</p>
<ul><li>Size A fits 6.5 to 7.5-inch wrist</li><li>Size B fits 7.5 to 8.5-inch wrist</li></ul>', 'https://longserviceawards.gww.gov.bc.ca/wp-content/uploads/2022/03/Earrings-bracelet-compass.jpg', -1, true);
INSERT INTO public.awards VALUES (26, '45-pearl-necklace', 'necklace', 45, 'Freshwater Pearl Necklace', '<p>Round freshwater pearls (6 - 6.5 mm) with a 14k yellow gold fisheye clasp. Comes with an engraved plate on the presentation box, "In recognition of forty-five years of service". </p><p>18 inches long.</p>', 'https://longserviceawards.gww.gov.bc.ca/wp-content/uploads/2023/03/45-pearl-necklace.jpg', -1, true);
INSERT INTO public.awards VALUES (27, '45-pearl-bracelet', 'bracelet', 45, 'Three-strand freshwater pearl bracelet', '<p>This beautiful freshwater pearl triple strand bracelet has 5 to 5.5 mm pearls with a sterling silver clasp. Size: 8"</p>', 'https://longserviceawards.gww.gov.bc.ca/wp-content/uploads/2022/03/pearl-bracelet-compass.jpg');


INSERT INTO public.awards VALUES (28, '50-whale-tail', 'print', 50, '"Whale Tail" Art Print', '<p>By B.C. artist Pauline Bull. Printed on canvas, framed in black with double groove. </p><p>  "In recognition of fifty years of service" is engraved on a plaque. Size: 18" x 24"</p>', 'https://longserviceawards.gww.gov.bc.ca/wp-content/uploads/2022/03/Whale-tail-print-compass.jpg', -1, false);
INSERT INTO public.awards VALUES (29, '50-pitcher', 'other', 50, 'Crystal Pitcher and Glass Set', '<p>Chesley, lead-free crystal, featuring a 50 oz. pitcher. Comes with four highball glasses, each 13 oz.</p>', 'https://longserviceawards.gww.gov.bc.ca/wp-content/uploads/2022/03/Crystal-set-with-glasses-compass.jpg', -1, false);
INSERT INTO public.awards VALUES (30, '50-citizen-watch', 'watch', 50, 'Citizen® Axiom Eco-Drive Watch', '<p>This 40mm watch features a black dial and black leather strap, a date feature and splash resistant casing. Comes in a stainless steel case. </p>', 'https://longserviceawards.gww.gov.bc.ca/wp-content/uploads/2022/03/Citizen-axiom-watch-large.jpg', -1, false);
INSERT INTO public.awards VALUES (31, '50-luggage', 'luggage', 50, 'Thule® Subterra Luggage', '<p>This durable luggage from Thule is made from water-resistant materials. The tough, oversized wheels and V-Tubing telescoping handles make for smooth and easy transport. It has a divided main compartment to separate clothes and has top, side and bottom handles. Complies with carry-on requirements for most airlines. Size: 21.7 x 13.8 x 7.9 inches.</p>', 'https://longserviceawards.gww.gov.bc.ca/wp-content/uploads/2022/03/45-thule-luggage-compass.jpg', -1, false);
INSERT INTO public.awards VALUES (32, '50-messenger-bag', 'luggage', 50, 'Leather Messenger Bag', '<p>Full grained distressed water buffalo tanned leather. Holds a standard laptop or tablet. Flap cover has magnetic closure. This bag has extra inside pockets and a canvas lining. Shoulder strap is adjustable.</p>', 'https://longserviceawards.gww.gov.bc.ca/wp-content/uploads/2022/03/messenger-bag-compass.jpg', -1, false);
INSERT INTO public.awards VALUES (33, '50-pearl-necklace', 'necklace', 50, 'Freshwater Pearl Necklace', '<p>Round freshwater pearls (6 - 6.5 mm) with a 14k yellow gold fisheye clasp. Comes with an engraved plate on the presentation box, "In recognition of fifty years of service." 18 inches long.</p>', 'https://longserviceawards.gww.gov.bc.ca/wp-content/uploads/2022/03/45-pearl-necklace-compass.jpg', -1, true);
INSERT INTO public.awards VALUES (34, '50-diamond-earrings', 'earrings', 50, 'Genuine Diamond Stud Earrings', '<p>These 14 kt white gold stud earrings feature brilliant round-cut diamonds, 0.30 carat total weight. The earrings have four white gold claws and butterfly backs. Presented in a box engraved with "In recognition of forty years of service."</p>', 'https://longserviceawards.gww.gov.bc.ca/wp-content/uploads/2022/03/diamond-earrings-compass.jpg', -1, true);
INSERT INTO public.awards VALUES (35, '50-earrings-bracelet', 'bracelet', 50, 'Sterling Silver Bracelet and Earrings', '<p>This matched set of sterling silver cuff bracelet and drop earrings are handcrafted by BC artists Nancy Dawson and Vincent Henson of Silver Eagles Design Studio. </p><p>  Presented in a box engraved with, "In recognition of fifty years of service."</p>', 'https://longserviceawards.gww.gov.bc.ca/wp-content/uploads/2022/03/Earrings-bracelet-compass.jpg', -1, true);
INSERT INTO public.awards VALUES (36, '50-clock-wall', 'clock', 50, 'Eastmont Wall clock', '<p>This beautiful Howard Miller wall clock is finished in Windsor cherry wood. This traditional pendulum wall clock features a broad pediment molding accented with deep embossing. The Roman numeral dial is surrounded by a polished brass bezel and features wrought black hands. The polished brass pendulum features a decorative lyre. Quartz battery operated, movement plays full Westminster or Ave Maria chimes. Volume control and nighttime volume reduction option are available. </p><p> 11.5" x 16.5" x 7" </p><p> "In recognition of fifty years of service," is engraved on a plaque. 11.5" x 16.5" x 7"</p>', 'https://longserviceawards.gww.gov.bc.ca/wp-content/uploads/2022/03/Eastmont-wall-clock-compass.jpg', -1, false);


INSERT INTO public.awards VALUES (37, '25-pecsf', 'pecsf', 25, 'PECSF Donation', '<p>Donate to the Provincial Employees Community Services Fund, an annual fundraising campaign that helps BC Public Service employees support local charities.</p>', 'https://longserviceawards.gww.gov.bc.ca/wp-content/uploads/2022/03/pecsf-logo-compass.jpg', -1, true);
INSERT INTO public.awards VALUES (38, '30-pecsf', 'pecsf', 30, 'PECSF Donation', '<p>Donate to the Provincial Employees Community Services Fund, an annual fundraising campaign that helps BC Public Service employees support local charities.</p>', 'https://longserviceawards.gww.gov.bc.ca/wp-content/uploads/2022/03/pecsf-logo-compass.jpg', -1, true);
INSERT INTO public.awards VALUES (39, '35-pecsf', 'pecsf', 35, 'PECSF Donation', '<p>Donate to the Provincial Employees Community Services Fund, an annual fundraising campaign that helps BC Public Service employees support local charities.</p>', 'https://longserviceawards.gww.gov.bc.ca/wp-content/uploads/2022/03/pecsf-logo-compass.jpg', -1, true);
INSERT INTO public.awards VALUES (40, '40-pecsf', 'pecsf', 40, 'PECSF Donation', '<p>Donate to the Provincial Employees Community Services Fund, an annual fundraising campaign that helps BC Public Service employees support local charities.</p>', 'https://longserviceawards.gww.gov.bc.ca/wp-content/uploads/2022/03/pecsf-logo-compass.jpg', -1, true);
INSERT INTO public.awards VALUES (41, '45-pecsf', 'pecsf', 45, 'PECSF Donation', '<p>Donate to the Provincial Employees Community Services Fund, an annual fundraising campaign that helps BC Public Service employees support local charities.</p>', 'https://longserviceawards.gww.gov.bc.ca/wp-content/uploads/2022/03/pecsf-logo-compass.jpg', -1, true);
INSERT INTO public.awards VALUES (42, '50-pecsf', 'pecsf', 50, 'PECSF Donation', '<p>Donate to the Provincial Employees Community Services Fund, an annual fundraising campaign that helps BC Public Service employees support local charities.</p>', 'https://longserviceawards.gww.gov.bc.ca/wp-content/uploads/2022/03/pecsf-logo-compass.jpg', -1, true);

-- Added in 2023
INSERT INTO public.awards VALUES (43, '25-wristlet', 'luggage', 25, 'Raven Embossed Wristlet', '<p>This great genuine leather wristlet is embossed with a Raven design by artist Corrine Hunt. </p><p> The bag is 7.5 inches long and 4 inches wide.</p>', ' https://longserviceawards.gww.gov.bc.ca/wp-content/uploads/2023/03/25-Raven-embossed-wristlet.jpg', -1, true);
INSERT INTO public.awards VALUES (44, '25-mug-set', 'other', 25, 'Coffee Press and Mug Set', '<p>This traditional, glass and bamboo French coffee press (20 oz.) comes with a 400 ml stoneware coffee mug. Set includes two Taylor''s tea bags, and a bag of William Spartivento fair trade coffee (brews 12 cups). Grind, and enjoy your favorite coffee or tea anywhere, anytime. Custom engraved with 25 years and the COA logo on both pieces.</p>', 'https://longserviceawards.gww.gov.bc.ca/wp-content/uploads/2023/03/25-coffee-press-and-mug-set.jpg', -1, true);
INSERT INTO public.awards VALUES (45, '25-gift-set', 'other', 25, 'Boxed Gift Set- Thermal bottle and tumbler - Plain Faux Leather', '<p>This set comes with a 16.9 oz. thermal bottle that has a faux leather sleeve. Stainless, leak proof cap. Made to keep drinks hot or cold. The matching 16.9 oz insulated stainless tumbler with plastic liner has a splash-resistant acrylic drink-thorough lid.</p> <p>Imprinted with 25 year and the COA logo (not exactly as shown).</p>', 'https://longserviceawards.gww.gov.bc.ca/wp-content/uploads/2023/03/25-thermal-bottle-and-tumbler.jpg', -1, true);


INSERT INTO public.awards VALUES (46, '30-tribune-bay', 'print', 30, 'Art Print “Tribune Bay"', '<p>Fine art paper with warm white matting, and inner black matting and black frame. By BC artist Misha Smart.</p> <p>Size approx. 16 x 18 inches.</p>
<p>Years of service engraved plate in matting of print.</p>', 'https://longserviceawards.gww.gov.bc.ca/wp-content/uploads/2023/03/30-Tribune-Bay.jpg', -1, true);
INSERT INTO public.awards VALUES (47, '30-best-friend', 'print', 30, 'Art Print “Best Friend at Sunset”', '<p>A beautiful paper art card with a black frame, warm cream toned matting and inner black matting. By Tlingit artist Mark Preston.</p><p>Size approx. 12 x 15 inches</p><p>Years of service engraved plate in matting of print.</p>', 'https://longserviceawards.gww.gov.bc.ca/wp-content/uploads/2023/03/30-Best-friend-at-sunset.jpg', -1, true);
INSERT INTO public.awards VALUES (48, '30-Giverny-Vase', 'glassware', 30, 'Giverny vase - small', '<p>This classic blown glass vase, is a stunning piece created by BC artist Robert Held.</p><p>Size: 5 inches tall</p><p>Due to the nature of the gift, no year of service plate</p>', 'https://longserviceawards.gww.gov.bc.ca/wp-content/uploads/2023/03/30-Giverny-vase-small.jpg', -1, true);


INSERT INTO public.awards VALUES (49, '35-Wave-Vase', 'glassware', 35, 'Wave Flower Bouquet Clear Vase', '<p>This whimsical example of Robert''s Flower Bouquet collection is referred to as a medium wave vase. Free formed, every piece is unique. The vase is lovely alone or filled with your favorite flowers.</p><p>By BC artist Robert Held </p><p>Medium vase stands approx.10 inches</p>', 'https://longserviceawards.gww.gov.bc.ca/wp-content/uploads/2023/03/35-wave-flower-vase.jpg', -1, true);


INSERT INTO public.awards VALUES (50, '40-Morning-Visit', 'print', 40, 'Art Print “Morning Visit"', '<p>Fine art paper framed double matted in deep brown and cream shades accented with a simple clean frame. By BC Artist Marvin Pelkey.</p><p>Size approx. 18 x 24 inches</p><p>Years of service engraved plate in matting of print</p>', 'https://longserviceawards.gww.gov.bc.ca/wp-content/uploads/2023/03/40-Morning-Visit.jpg', -1, true);


INSERT INTO public.awards VALUES (51, '45-Swept-Away', 'print', 45, 'Art Print “Swept Away“', '<p>Poster framed with gray frame, off white matting, and gray inner matting. By BC artist Jennifer Harwood.</p><p>Size approx.: 17 x 28 inches.</p><p>Years of service engraved plate in matting.</p>', 'https://longserviceawards.gww.gov.bc.ca/wp-content/uploads/2023/03/45-50-Swept-Away.jpg', -1, true);
INSERT INTO public.awards VALUES (52, '45-Tasco-Telescope', 'other', 45, 'TASCO 900 x 114 Luminova Reflector Telescope', '<p>A full-featured 900mm focal length reflector telescope for beginning and intermediate astronomy enthusiasts.</p><p>Specifications:</p><ul><li>675x 4.5" Reflector</li><li>
Mount : Equatorial 1</li><li>Finderscope: 6 x 24 mm</li><li>Focal Ration: F/8</li><li>Eyepiece( 1.25")H 25 MM (36x0 H12.5 (72x, SR4mm (225x)</li><li>Tripod: Adjustable, aluminum</li><li>Wt.(lbs./kg): 32/14.5</li><li>Accessories: Tasco skywatch CD-Rom, 3x Barlow Lens, Moon filter.</li></ul></p>', 'https://longserviceawards.gww.gov.bc.ca/wp-content/uploads/2023/03/45-TASCO-telescope.jpg', -1, true);
INSERT INTO public.awards VALUES (53, '45-Heys-luggage', 'luggage', 45, 'Heys Vantage 26" Smart Access- Luggage - black', '<p>Smart Access is a new and innovative patented system that will reinvent the way you pack luggage. With its front-access compartment, removable divider, and spacious main compartment, the Vantage Smart Access offers versatility to packing that allows for easy organization. Front-access system allows luggage to be easily accessible, making packing easier and more organized. Carry-on size features front-access compartment, with cushioned pocket that fits up to 15.6" laptops. Made from 100% pure Polycarbonate, the most durable. 360 dual spinner wheels. 
</p><p>Exterior 16.25 "W x 26"h x 10.25" deep</p>', 'https://longserviceawards.gww.gov.bc.ca/wp-content/uploads/2023/03/45-50-Heys-luggage.jpg', -1, true);

INSERT INTO public.awards VALUES (54, '50-Swept-Away', 'print', 50, 'Art Print “Swept Away“', '<p>Poster framed with gray frame, off white matting, and gray inner matting. By BC artist Jennifer Harwood.</p><p>Size approx.: 17 x 28 inches.</p><p>Years of service engraved plate in matting.</p>', 'https://longserviceawards.gww.gov.bc.ca/wp-content/uploads/2023/03/45-50-Swept-Away.jpg', -1, true);
INSERT INTO public.awards VALUES (55, '50-Giverny-Vase', 'glassware', 50, 'Giverny, Medium Round Vase with Lip', '<p>Contemporary in design, this lovely piece is hand blown in aqua blue and light green with a spray of golden lily pads, a beautiful example of Robert Held’s popular Giverny Collection.</p><p>Size approx. 6 inches x 7 inches</p><p>Due to the nature of the gift no year of service plate.</p>', 'https://longserviceawards.gww.gov.bc.ca/wp-content/uploads/2023/03/50-Giverny-vase.jpg', -1, true);
INSERT INTO public.awards VALUES (56, '50-knife-set', 'other', 50, 'Oneida By Lenox Preferred 18Pc. Stainless Steel Knife Set', '<p>The Oneida Preferred 18pc. Stainless Steel Knife Set consists of high quality knives with a variety of essential and precise blades and shapes with comfortable handles. Plus, the stylish and functional block will keep your set safe while being visually pleasing on the kitchen counter.</p><p>Quality stainless steel construction Peened handles Limited Lifetime Warranty.</p><p>Includes:</p><ul><li>8” Chef''s knife</li>
<li>7” Santoku knife</li><li>8” Carving knife</li><li>6” Chef''s knife</li><li>8” Bread knife</li><li>5” Utility knife</li><li>3” Paring knife</li><li>Teak knives (8)</li><li>Kitchen shears</li><li>Honing steel</li><li>Hardwood block</li></ul><p>“In recognition of fifty years of service" on plate</p>', 'https://longserviceawards.gww.gov.bc.ca/wp-content/uploads/2023/03/50-Knife-set.jpg', -1, true);
INSERT INTO public.awards VALUES (57, '50-clock-mantel', 'clock', 50, 'Statesboro Mantel clock', '<p>This veneered hardwood clock has a Cherry Bordeaux finish for stately style. Decorative olive ash burl-finished overlays adorn the front of this timepiece, which has gold detail on the side glass panels for an upscale touch. Plays the Westminster chime on the hour and an hour strike that will count the hour. Automatic nighttime silencing between 9:00 pm and 6:00 am.</p><p>Overall size: 9.5” w x 6.25” depth x 11.75 h.</p><p>“In recognition of Fifty years of service” engraved on a plaque.</p>', 'https://longserviceawards.gww.gov.bc.ca/wp-content/uploads/2023/03/50-Statesboro-mantel-clock.jpg', -1, true);
INSERT INTO public.awards VALUES (58, '50-Heys-luggage', 'luggage', 50, 'Heys Vantage 26" Smart Access- Luggage - black', '<p>Smart Access is a new and innovative patented system that will reinvent the way you pack luggage. With its front-access compartment, removable divider, and spacious main compartment, the Vantage Smart Access offers versatility to packing that allows for easy organization. Front-access system allows luggage to be easily accessible, making packing easier and more organized. Carry-on size features front-access compartment, with cushioned pocket that fits up to 15.6" laptops. Made from 100% pure Polycarbonate, the most durable. 360 dual spinner wheels. 
</p><p>Exterior 16.25 "W x 26"h x 10.25" deep</p>', 'https://longserviceawards.gww.gov.bc.ca/wp-content/uploads/2023/03/45-50-Heys-luggage.jpg', -1, true);
-- Updates for 2024
-- New watch added to maintain record of previous engravings and options
INSERT INTO public.awards VALUES (60, '35-bulova', 'watch', 35, 'Bulova® watch', '<p>This watch features the BC Coat of Arms on the dial and can be personalized with your name and "35 years" engraved on the back. It comes in a choice of gold, silver or two-toned construction with a plated, black or brown leather strap.</p><p>Please read and select from the following options carefully.</p>', 'https://longserviceawards.gww.gov.bc.ca/wp-content/uploads/2023/03/35-Bulova-watches.jpg', -1, true);

--
-- TOC entry 3428 (class 0 OID 0)
-- Dependencies: 223
-- Name: awards_id_seq; Type: SEQUENCE SET; Schema: public; Owner: lsa
--

SELECT pg_catalog.setval('public.awards_id_seq', 61, false);



-- Completed on 2023-01-29 14:59:51 PST

--
-- PostgreSQL database dump complete
--

